### ISSUE TITLE
query should be able to specify redirect uri

### ISSUE THREAD

**Issue by nsolter** [krishamoud/meteor-accounts-slack#1]
For installed clients like ios apps, the redirect comes back to the phone, and the call to the meteor server to exchange the code for a token is made explicitly. Slack requires the token exchange call to specify a redirect uri that has to match the original redirect uri used for obtaining the code. Thus, the installed clients need to be able to pass a redirect uri into the accounts-slack getAccessToken() method that can override the default.

**Comment by krishamoud** [comment]
Merged
